name: building

on:
  push:
    branches:
      - '**'
    tags-ignore:
      # Do not build on version tags to avoid racing npm publish with main branch
      - v**
      - latest
      - beta

jobs:
  try-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn in-one-go
